version: '3.9'

services:
  db:
    build:
        context: ./sqlserver/
    image: my-postgres-image
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
      
networks:
  default:
    name: Bet